const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
module.exports=async({app,win,commit,getState,dataFile,model})=>{
  const root=process.env.CHIAKI_QA_ROOT?path.resolve(process.env.CHIAKI_QA_ROOT):path.resolve(__dirname,'../.qa');await fs.mkdir(root,{recursive:true});
  const errors=[];win.webContents.on('console-message',(_e,...args)=>{const info=args[0];if(typeof info==='object'&&info.level==='error')errors.push(info.message);});
  const js=code=>win.webContents.executeJavaScript(code,true);
  const sleep=n=>new Promise(r=>setTimeout(r,n));
  const until=async(code)=>{for(let i=0;i<100;i++){if(await js(code))return;await sleep(50);}throw new Error('UI condition timed out: '+code);};
  const click=selector=>js(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const value=(selector,text)=>js(`document.querySelector(${JSON.stringify(selector)}).value=${JSON.stringify(text)}`);
  const setFilter=async(key,val)=>{if(!await js('!!document.querySelector(".filter-popover")'))await click('[data-action="filters-toggle"]');await value(`[data-filter="${key}"]`,val);await js(`document.querySelector('[data-filter="${key}"]').dispatchEvent(new Event('change',{bubbles:true}))`);};
  const reload=async()=>{await js('window.__chiakiReady=false');win.webContents.reload();await sleep(200);await until('window.__chiakiReady === true');await until('[...document.images].every(i=>i.complete && i.naturalWidth>0)');};
  const saved=()=>until('document.querySelector("#save-status").textContent.includes("保存在此电脑")');
  const screenshot=async(name)=>{const key=await win.webContents.insertCSS('*{animation:none!important;transition:none!important}');await win.webContents.capturePage(undefined,{stayHidden:true});await sleep(150);const shot=await win.webContents.capturePage(undefined,{stayHidden:true});await fs.writeFile(path.join(root,name+'.png'),shot.toPNG());await win.webContents.removeInsertedCSS(key);};
  const checks=[];const check=(name,fn)=>{fn();checks.push(name);console.log('PASS '+name);};
  const calendarWheelChaining=async(label)=>{
    win.webContents.debugger.attach('1.3');
    try{
      const geometry=()=>js(`(()=>{const c=document.querySelector('.calendar-content'),a=document.querySelector('.calendar-agenda'),r=a.getBoundingClientRect(),v=c.getBoundingClientRect();return {outer:c.scrollTop,inner:a.scrollTop,innerMax:a.scrollHeight-a.clientHeight,x:Math.round(r.left+r.width/2),y:Math.round(Math.min(r.top+70,v.bottom-20))};})()`);
      const wheel=async(deltaY)=>{await win.webContents.capturePage(undefined,{stayHidden:true});await sleep(150);const p=await geometry();await win.webContents.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mouseMoved',x:p.x,y:p.y});await win.webContents.debugger.sendCommand('Input.dispatchMouseEvent',{type:'mouseWheel',x:p.x,y:p.y,deltaX:0,deltaY});await sleep(400);await win.webContents.capturePage(undefined,{stayHidden:true});};
      const bottom=()=>js(`(()=>{const c=document.querySelector('.calendar-content'),a=document.querySelector('.calendar-agenda');c.scrollTop=c.scrollHeight;a.scrollTop=0;})()`);
      await click(`.calendar-day[data-date="${model.localDate()}"]`);await bottom();await sleep(100);
      const before=await geometry();assert.ok(before.outer>0&&before.innerMax>0,'Fixture must have scrollable calendar and busy agenda');
      await wheel(-120);assert.ok((await geometry()).outer<before.outer,label+' upward wheel at agenda top returns to calendar: '+JSON.stringify({before,after:await geometry()}));
      await bottom();await sleep(100);await wheel(100);assert.ok((await geometry()).inner>0,label+' wheel still scrolls long agenda');
      await js(`(()=>{const c=document.querySelector('.calendar-content'),a=document.querySelector('.calendar-agenda');c.scrollTop=Math.max(0,c.scrollHeight-c.clientHeight-100);a.scrollTop=a.scrollHeight;})()`);await sleep(100);
      const down=await geometry();await wheel(120);assert.ok((await geometry()).outer>down.outer,label+' downward wheel at agenda bottom continues outer scrolling');
      const empty=await js(`[...document.querySelectorAll('.calendar-day')].find(d=>!d.classList.contains('outside-month')&&!d.querySelector('.day-count')).dataset.date`);
      await click(`.calendar-day[data-date="${empty}"]`);await bottom();await sleep(100);const blank=await geometry();assert.equal(blank.innerMax,0);await wheel(-120);assert.ok((await geometry()).outer<blank.outer,label+' empty agenda also permits upward calendar scrolling');
      await click(`.calendar-day[data-date="${model.localDate()}"]`);await js('document.querySelector(".calendar-content").scrollTop=0;document.querySelector(".calendar-agenda").scrollTop=0');
      checks.push(label+' real wheel input chains between daily agenda and calendar at both boundaries');
    }finally{win.webContents.debugger.detach();}
  };
  const stableCalendarSelection=async(label)=>{
    const dates=await js(`(()=>{const month=document.querySelector('.month-calendar').dataset.month.slice(0,7);const days=[...document.querySelectorAll('.calendar-day')].filter(d=>d.dataset.date.startsWith(month));return [days.find(d=>Number(d.querySelector('.day-count')?.textContent)>2),days.find(d=>d.querySelector('.day-count')?.textContent==='1'),days.find(d=>!d.querySelector('.day-count'))].map(d=>d.dataset.date);})()`);
    const geometry=()=>js(`(()=>{const c=document.querySelector('.calendar-content'),r=document.querySelector('.calendar-grid').getBoundingClientRect();return {top:r.top,left:r.left,width:r.width,scroll:c.scrollTop,height:c.scrollHeight};})()`);
    await js('window.__calendarGrid=document.querySelector(".calendar-grid");window.__calendarArt=document.querySelector(".companion-panel");');
    for(const scroll of [0,60]){
      await js(`document.querySelector('.calendar-content').scrollTop=${scroll}`);
      for(const date of [...dates,...dates.toReversed()]){
        const before=await geometry();await click(`.calendar-day[data-date="${date}"]`);
        for(const delay of [100,450]){await sleep(delay);const after=await geometry();for(const key of Object.keys(before))assert.ok(Math.abs(before[key]-after[key])<0.5,`${label}: ${key} moved from ${before[key]} to ${after[key]} on ${date}`);}
        assert.equal(await js('document.querySelector(".selected-day").dataset.date'),date);
        assert.equal(await js('document.querySelectorAll(".calendar-agenda [data-task]").length'),getState().tasks.filter(t=>!t.completed&&t.dueDate===date).length);
      }
    }
    assert.ok(await js('window.__calendarGrid===document.querySelector(".calendar-grid") && window.__calendarArt===document.querySelector(".companion-panel")'));
    const before=await geometry();await js(`(()=>{const d=document.querySelector('.calendar-day[data-date="${dates[0]}"]');d.focus({preventScroll:true});d.dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true}));})()`);await sleep(550);assert.deepEqual(await geometry(),before);
    assert.equal(await js(`document.querySelector('.calendar-day[data-date="${dates[0]}"]').getAttribute('aria-pressed')`),'true');
    await js('document.querySelector(".calendar-content").scrollTop=0');
    checks.push(label+' date clicks and keyboard selection keep calendar position with empty and busy days');
  };
  try{
    await until('window.__chiakiReady === true');
    assert.equal(win.getTitle(),'千秋万待');
    assert.equal(await js('document.title'),'千秋万待');
    assert.equal(await js('document.querySelector(".brand strong").textContent'),'千秋万待');
    assert.ok((await js('document.querySelector(".titlebar-name").textContent')).includes('千秋万待'));
    checks.push('renamed app title, sidebar brand and window title');
    if(process.argv.includes('--screenshot-only')){
      await commit(model.demoState());await reload();await screenshot('caption-today');
      win.setSize(1060,700);await sleep(150);await screenshot('caption-compact');
      console.log('Caption previews captured');app.exit(0);return;
    }
    await commit(model.initialState());await reload();await screenshot('empty');
    await click('[data-action="new-task"]');
    await value('#task-title','<img src=x onerror=alert(1)> 本地测试待办');
    await value('[name="notes"]','验证保存、子任务与重复');await value('[name="tags"]','学习，项目，学习');
    await value('[name="priority"]','high');
    await js('document.querySelector("[name=important]").checked=true;document.querySelector("[name=urgent]").checked=true;');
    await value('[name="repeat"]','daily');
    await value('#subtask-input','第一步');await click('[data-action="add-subtask"]');
    await js('document.querySelector("#task-form").requestSubmit()');await saved();
    check('create task and save on disk',()=>{assert.equal(getState().tasks.length,1);assert.equal(getState().tasks[0].priority,'high');assert.equal(getState().tasks[0].subtasks.length,1);});
    check('task tags saved and deduplicated',()=>assert.deepEqual(getState().tasks[0].tags,['学习','项目']));
    check('escaped task title',()=>assert.equal(getState().tasks[0].title,'<img src=x onerror=alert(1)> 本地测试待办'));
    assert.equal(await js('document.querySelectorAll(".task-content img").length'),0);
    await reload();assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);checks.push('restart reload persisted task');
    await click('[data-action="complete"]');await saved();
    check('complete recurrence creates next local date',()=>{assert.equal(getState().tasks.length,2);assert.equal(getState().tasks[1].dueDate,model.addDays(model.localDate(),1));});
    await click('[data-action="undo"]');await saved();
    check('undo also removes repeat successor',()=>assert.equal(getState().tasks.length,1));
    await click('[data-view="matrix"]');
    await js(`(()=>{const row=document.querySelector('[data-task]');const zone=document.querySelector('[data-drop-quadrant="plan"]');const data=new DataTransfer();row.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:data}));zone.dispatchEvent(new DragEvent('dragover',{bubbles:true,dataTransfer:data}));zone.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:data}));})()`);await saved();
    check('drag between quadrants updates properties',()=>{assert.equal(getState().tasks[0].important,true);assert.equal(getState().tasks[0].urgent,false);});
    assert.equal(await js('document.querySelectorAll(".sidebar [data-view]").length'),4);
    for(let i=0;i<3;i++){await click('[data-view="matrix"]');assert.equal(await js('document.querySelectorAll(".quadrant").length'),4);await click('[data-view="all"]');assert.equal(await js('document.querySelectorAll(".quadrant").length'),0);assert.equal(await js('document.querySelector(".page-header h1").textContent'),'全部待办');}
    checks.push('all tasks sidebar reliably returns from quadrants to list');
    await setFilter('important','yes');await click('[data-filter-array="listIds"][value="work"]');
    assert.equal(await js('document.querySelectorAll("[data-task]").length'),0);
    await click('[data-action="filter-remove"][data-value="work"]');assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);
    await click('[data-filter-array="listIds"][value="personal"]');
    await click('[data-action="layout"][data-value="matrix"]');assert.equal(await js('document.querySelectorAll(".quadrant").length'),4);assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);
    await click('[data-view="scheduled"]');await click('[data-view="all"]');assert.equal(await js('document.querySelectorAll(".quadrant").length'),0);assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);assert.ok(await js(`!!document.querySelector('[data-action="filter-remove"][data-value="personal"]')`));
    checks.push('list and quadrant switching preserves combined filters and sidebar list returns');
    await click('[data-action="filters-reset"]');await click('[data-action="filters-toggle"]');await click('[data-action="manage-lists"]');await click('[data-action="new-list"]');await value('#list-name','自定义清单');await js('document.querySelector("#list-form").requestSubmit()');await saved();
    check('manage and create lists inside filtering controls',()=>assert.ok(getState().lists.some(l=>l.name==='自定义清单')));
    await click('[data-action="settings"]');await click('[data-setting="theme"]');await saved();
    check('dark mode persists',()=>assert.equal(getState().settings.theme,'dark'));
    assert.equal(await js('getComputedStyle(document.body).backgroundColor'),'rgb(37, 37, 41)');checks.push('dark mode renders correct colors');
    await click('[data-action="close-modal"]');
    await value('#focus-duration','37');await js('document.querySelector("#focus-duration").dispatchEvent(new Event("change",{bubbles:true}))');await saved();assert.equal(getState().settings.focusMinutes,37);assert.equal(await js('document.querySelector("#focus-time").textContent'),'37:00');
    await value('#focus-duration','0');await js('document.querySelector("#focus-duration").dispatchEvent(new Event("change",{bubbles:true}))');assert.equal(getState().settings.focusMinutes,37);assert.equal(await js('document.querySelector("#focus-duration").value'),'37');
    await reload();assert.equal(await js('document.querySelector("#focus-duration").value'),'37');
    await click('[data-action="timer"]');await saved();assert.ok(getState().timer.end-Date.now()>36*60000);assert.ok(await js('document.querySelector("#focus-duration").disabled'));
    checks.push('custom focus minutes persist, reject invalid values and start correct duration');
    await click('[data-action="timer"]');await saved();
    check('paused focus timer is persisted',()=>{assert.equal(getState().timer.end,null);assert.ok(getState().timer.remaining>0);});
    await reload();assert.ok((await js('document.querySelector(".focus-start").textContent')).includes('继续'));checks.push('paused timer survives restart');
    const fixture=model.demoState();fixture.tasks[0].tags=['项目'];fixture.tasks[1].tags=['学习'];fixture.tasks[4].tags=['学习'];await commit(fixture);await reload();
    await click('[data-view="all"]');await setFilter('important','yes');await click('[data-filter-array="listIds"][value="work"]');await setFilter('priority','medium');assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);
    await click('[data-filter-array="listIds"][value="personal"]');await click('[data-filter-array="tags"][value="学习"]');await setFilter('urgent','no');await setFilter('date','week');await setFilter('repeat','no');await setFilter('subtasks','no');assert.equal(await js('document.querySelectorAll("[data-task]").length'),2);await screenshot('filters');
    await click('[data-action="filters-toggle"]');await value('#sort-select','title');await js('document.querySelector("#sort-select").dispatchEvent(new Event("change",{bubbles:true}))');await saved();
    const rows=await js('[...document.querySelectorAll("[data-task]")].map(t=>t.dataset.task)');const expected=fixture.tasks.filter(t=>['读一会儿喜欢的书','整理这个月的学习笔记'].includes(t.title)).sort((a,b)=>a.title.localeCompare(b.title,'zh-CN',{numeric:true})).map(t=>t.id);assert.deepEqual(rows,expected);
    checks.push('multiple list, tag, feature and date filters combine with title sorting');
    await click('[data-action="filters-reset"]');await click('[data-action="filter-tag"][data-tag="项目"]');assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);assert.equal(await js('document.querySelectorAll("#overlay-root .dialog").length'),0);await click('[data-action="filters-reset"]');
    await setFilter('status','completed');assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);const done=fixture.tasks.find(t=>t.completed);await click(`[data-action="complete"][data-id="${done.id}"]`);await saved();assert.equal(await js('document.querySelectorAll("[data-task]").length'),0);assert.equal(getState().tasks.find(t=>t.id===done.id).completed,false);
    checks.push('completed tasks are filtered and can be restored in the same list');
    await commit(model.demoState());await reload();await screenshot('today');
    await click('[data-view="scheduled"]');
    const today=model.localDate(),date=model.addDays(today,2);
    const todayCount=getState().tasks.filter(t=>!t.completed&&t.dueDate===today).length;
    assert.equal(await js(`document.querySelector('.calendar-day[data-date="${today}"] .day-count').textContent`),String(todayCount));
    assert.equal(await js('document.querySelectorAll(".calendar-agenda [data-task]").length'),todayCount);
    assert.equal(await js(`document.querySelectorAll('.calendar-day[data-date="${today}"] .calendar-task').length`),2);
    assert.equal(await js(`document.querySelector('.calendar-day[data-date="${today}"] .calendar-more').textContent`),'＋'+(todayCount-2)+' 件');
    checks.push('calendar displays daily task names, overflow count and full selected-day agenda');
    await stableCalendarSelection('full window');
    await click(`.calendar-day[data-date="${date}"]`);await click('[data-action="new-task"]');
    assert.equal(await js('document.querySelector("[name=dueDate]").value'),date);
    await value('#task-title','日历新建验证');await js('document.querySelector("#task-form").requestSubmit()');await saved();
    check('new task uses selected calendar day',()=>assert.equal(getState().tasks.find(t=>t.title==='日历新建验证').dueDate,date));
    await value('.calendar-agenda .quick-add input','日历快速添加验证');await js('document.querySelector(".calendar-agenda .quick-add").requestSubmit()');await saved();
    check('quick add uses selected calendar day',()=>assert.equal(getState().tasks.find(t=>t.title==='日历快速添加验证').dueDate,date));
    const added=getState().tasks.find(t=>t.title==='日历新建验证'),moved=model.addDays(date,1);
    await click(`.calendar-task[data-id="${added.id}"]`);await value('[name=dueDate]',moved);await js('document.querySelector("#task-form").requestSubmit()');await saved();
    assert.equal(await js(`document.querySelector('.calendar-day[data-date="${moved}"] .day-count').textContent`),String(getState().tasks.filter(t=>!t.completed&&t.dueDate===moved).length));
    checks.push('editing date moves task to the correct calendar day');
    const quick=getState().tasks.find(t=>t.title==='日历快速添加验证');
    await click(`.calendar-agenda [data-action="complete"][data-id="${quick.id}"]`);await saved();
    assert.equal(await js(`document.querySelectorAll('.calendar-task[data-id="${quick.id}"]').length`),0);
    check('calendar completion saves and removes pending day marker',()=>assert.ok(getState().tasks.find(t=>t.id===quick.id).completed));
    await value('#calendar-month','2026-12');await js('document.querySelector("#calendar-month").dispatchEvent(new Event("change",{bubbles:true}))');
    await click('[data-action="calendar-month"][data-offset="1"]');
    assert.equal(await js('document.querySelector("#calendar-month").value'),'2027-01');
    await value('#calendar-month','2028-02');await js('document.querySelector("#calendar-month").dispatchEvent(new Event("change",{bubbles:true}))');
    assert.equal(await js(`document.querySelectorAll('.calendar-day[data-date="2028-02-29"]').length`),1);
    await click('.calendar-day[data-date="2028-01-31"]');
    assert.equal(await js('document.querySelector("#calendar-month").value'),'2028-01');
    await click('[data-action="calendar-today"]');
    assert.equal(await js('document.querySelector(".selected-day").dataset.date'),today);
    checks.push('calendar handles year change, leap day, adjacent month and return to today');
    await commit(model.demoState());await reload();await click('[data-view="scheduled"]');await calendarWheelChaining('full window');await screenshot('calendar');
    win.setSize(1060,700);await sleep(200);await calendarWheelChaining('compact window');await stableCalendarSelection('compact window');await screenshot('calendar-compact');
    await value('#calendar-month','2026-08');await js('document.querySelector("#calendar-month").dispatchEvent(new Event("change",{bubbles:true}))');await screenshot('calendar-six-weeks');
    assert.equal(await js('document.querySelectorAll(".calendar-day").length'),42);
    assert.ok(await js('document.body.scrollWidth<=innerWidth && document.querySelector(".calendar-grid").scrollWidth<=document.querySelector(".calendar-grid").clientWidth'));
    assert.ok(await js('document.querySelector(".calendar-grid").getBoundingClientRect().bottom<=document.querySelector(".calendar-content").getBoundingClientRect().bottom'));
    checks.push('compact six-week calendar fits window width');
    win.setSize(1440,930);await sleep(200);await click('[data-action="calendar-today"]');
    await click('[data-view="matrix"]');await screenshot('matrix');
    await click('[data-action="edit-task"]');await screenshot('task-editor');await click('[data-action="close-modal"]');
    await click('[data-action="settings"]');await click('[data-setting="theme"]');await saved();await click('[data-action="close-modal"]');await screenshot('dark');
    await click('[data-action="settings"]');await click('[data-setting="theme"]');await saved();await click('[data-action="close-modal"]');
    win.setSize(1060,700);await sleep(300);await click('[data-view="all"]');await setFilter('status','all');await screenshot('filters-compact');assert.ok(await js('(()=>{const r=document.querySelector(".filter-popover").getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;})()'));await click('[data-action="filters-reset"]');await click('[data-action="filters-toggle"]');await screenshot('compact');
    const overflows=await js(`(()=>{const el=document.querySelector('.workspace');return {width:el.scrollWidth,client:el.clientWidth,body:document.body.scrollWidth,viewport:window.innerWidth};})()`);
    check('minimum window does not overflow horizontally',()=>assert.ok(overflows.body<=overflows.viewport&&overflows.width<=overflows.client));
    win.setSize(1440,930);await sleep(200);await click('[data-view="all"]');
    await click('[data-action="search"]');await value('#search-form input','第一版');await js('document.querySelector("#search-form").requestSubmit()');
    assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);checks.push('global search filters results');
    await click('[data-action="clear-search"]');await setFilter('status','completed');assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);checks.push('completed filter in task list');
    const stored=JSON.parse(await fs.readFile(dataFile,'utf8'));assert.equal(stored.tasks.length,8);assert.ok((await fs.stat(path.join(path.dirname(dataFile),'tasks.backup.json'))).size>0);checks.push('atomic file save and recovery snapshot');
    assert.deepEqual(errors,[]);checks.push('no renderer errors');
    await fs.writeFile(path.join(root,'test-results.json'),JSON.stringify({passed:checks.length,checks,errors},null,2),'utf8');
    console.log(`Desktop checks passed: ${checks.length}`);app.exit(0);
  }catch(e){console.error(e);await fs.writeFile(path.join(root,'test-results.json'),JSON.stringify({passed:checks.length,checks,error:e.stack,errors},null,2));try{await screenshot('failure');}catch{}app.exit(1);}
};
