const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
module.exports=async({app,win,commit,getState,dataFile,model})=>{
  const root=process.env.CHIAKI_QA_ROOT?path.resolve(process.env.CHIAKI_QA_ROOT):path.resolve(__dirname,'../.qa');await fs.mkdir(root,{recursive:true});
  const errors=[];win.webContents.on('console-message',(_e,...args)=>{const info=args[0];if(typeof info==='object'&&info.level==='error')errors.push(info.message);});
  const js=code=>win.webContents.executeJavaScript(code,true);
  const sleep=n=>new Promise(r=>setTimeout(r,n));
  const until=async(code)=>{for(let i=0;i<100;i++){if(await js(code))return;await sleep(50);}throw new Error('UI condition timed out: '+code);};
  const click=selector=>js(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const value=(selector,text)=>js(`document.querySelector(${JSON.stringify(selector)}).value=${JSON.stringify(text)}`);
  const reload=async()=>{await js('window.__chiakiReady=false');win.webContents.reload();await sleep(200);await until('window.__chiakiReady === true');await until('[...document.images].every(i=>i.complete && i.naturalWidth>0)');};
  const saved=()=>until('document.querySelector("#save-status").textContent.includes("保存在此电脑")');
  const screenshot=async(name)=>{const key=await win.webContents.insertCSS('*{animation:none!important;transition:none!important}');await win.webContents.capturePage(undefined,{stayHidden:true});await sleep(150);const shot=await win.webContents.capturePage(undefined,{stayHidden:true});await fs.writeFile(path.join(root,name+'.png'),shot.toPNG());await win.webContents.removeInsertedCSS(key);};
  const checks=[];const check=(name,fn)=>{fn();checks.push(name);console.log('PASS '+name);};
  try{
    await until('window.__chiakiReady === true');
    assert.equal(win.getTitle(),'千秋万待');
    assert.equal(await js('document.title'),'千秋万待');
    assert.equal(await js('document.querySelector(".brand strong").textContent'),'千秋万待');
    assert.ok((await js('document.querySelector(".titlebar-name").textContent')).includes('千秋万待'));
    checks.push('renamed app title, sidebar brand and window title');
    if(process.argv.includes('--screenshot-only')){
      await commit(model.demoState());await reload();await screenshot('caption-today');
      win.setSize(1060,700);await sleep(150);await screenshot('caption-compact');
      console.log('Caption previews captured');app.exit(0);return;
    }
    await commit(model.initialState());await reload();await screenshot('empty');
    await click('[data-action="new-task"]');
    await value('#task-title','<img src=x onerror=alert(1)> 本地测试待办');
    await value('[name="notes"]','验证保存、子任务与重复');
    await value('[name="priority"]','high');
    await js('document.querySelector("[name=important]").checked=true;document.querySelector("[name=urgent]").checked=true;');
    await value('[name="repeat"]','daily');
    await value('#subtask-input','第一步');await click('[data-action="add-subtask"]');
    await js('document.querySelector("#task-form").requestSubmit()');await saved();
    check('create task and save on disk',()=>{assert.equal(getState().tasks.length,1);assert.equal(getState().tasks[0].priority,'high');assert.equal(getState().tasks[0].subtasks.length,1);});
    check('escaped task title',()=>assert.equal(getState().tasks[0].title,'<img src=x onerror=alert(1)> 本地测试待办'));
    assert.equal(await js('document.querySelectorAll(".task-content img").length'),0);
    await reload();assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);checks.push('restart reload persisted task');
    await click('[data-action="complete"]');await saved();
    check('complete recurrence creates next local date',()=>{assert.equal(getState().tasks.length,2);assert.equal(getState().tasks[1].dueDate,model.addDays(model.localDate(),1));});
    await click('[data-action="undo"]');await saved();
    check('undo also removes repeat successor',()=>assert.equal(getState().tasks.length,1));
    await click('[data-view="matrix"]');
    await js(`(()=>{const row=document.querySelector('[data-task]');const zone=document.querySelector('[data-drop-quadrant="plan"]');const data=new DataTransfer();row.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:data}));zone.dispatchEvent(new DragEvent('dragover',{bubbles:true,dataTransfer:data}));zone.dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:data}));})()`);await saved();
    check('drag between quadrants updates properties',()=>{assert.equal(getState().tasks[0].important,true);assert.equal(getState().tasks[0].urgent,false);});
    for(const target of ['list:work','list:personal','today','priority','all']){
      await click(`[data-view="${target}"]`);
      assert.equal(await js('document.querySelectorAll(".quadrant").length'),4);
      assert.equal(await js('document.querySelectorAll("[data-task]").length'),model.filteredTasks(getState(),target).length);
    }
    checks.push('sidebar filters tasks without resetting quadrant layout');
    await click('[data-view="list:personal"]');await click('[data-action="layout"][data-value="list"]');
    assert.equal(await js('document.querySelectorAll(".quadrant").length'),0);
    assert.equal(await js('document.querySelector(".page-header h1").textContent'),'个人');
    await click('[data-action="layout"][data-value="matrix"]');
    assert.equal(await js('document.querySelector(".page-header h1").textContent'),'个人');
    await click('[data-view="scheduled"]');await click('[data-view="list:personal"]');
    assert.equal(await js('document.querySelectorAll(".quadrant").length'),4);
    checks.push('list and quadrant toggles preserve list scope across calendar navigation');
    await click('[data-action="new-list"]');await value('#list-name','自定义清单');await js('document.querySelector("#list-form").requestSubmit()');await saved();
    check('create custom list',()=>assert.ok(getState().lists.some(l=>l.name==='自定义清单')));
    await click('[data-action="settings"]');await click('[data-setting="theme"]');await saved();
    check('dark mode persists',()=>assert.equal(getState().settings.theme,'dark'));
    assert.equal(await js('getComputedStyle(document.body).backgroundColor'),'rgb(37, 37, 41)');checks.push('dark mode renders correct colors');
    await click('[data-action="close-modal"]');
    await click('[data-action="timer"]');await saved();assert.ok(getState().timer.end>Date.now());
    await click('[data-action="timer"]');await saved();
    check('paused focus timer is persisted',()=>{assert.equal(getState().timer.end,null);assert.ok(getState().timer.remaining>0);});
    await reload();assert.ok((await js('document.querySelector(".focus-start").textContent')).includes('继续'));checks.push('paused timer survives restart');
    await commit(model.demoState());await reload();await screenshot('today');
    await click('[data-view="scheduled"]');
    const today=model.localDate(),date=model.addDays(today,2);
    const todayCount=getState().tasks.filter(t=>!t.completed&&t.dueDate===today).length;
    assert.equal(await js(`document.querySelector('.calendar-day[data-date="${today}"] .day-count').textContent`),String(todayCount));
    assert.equal(await js('document.querySelectorAll(".calendar-agenda [data-task]").length'),todayCount);
    assert.equal(await js(`document.querySelectorAll('.calendar-day[data-date="${today}"] .calendar-task').length`),2);
    assert.equal(await js(`document.querySelector('.calendar-day[data-date="${today}"] .calendar-more').textContent`),'＋'+(todayCount-2)+' 件');
    checks.push('calendar displays daily task names, overflow count and full selected-day agenda');
    await click(`.calendar-day[data-date="${date}"]`);await click('[data-action="new-task"]');
    assert.equal(await js('document.querySelector("[name=dueDate]").value'),date);
    await value('#task-title','日历新建验证');await js('document.querySelector("#task-form").requestSubmit()');await saved();
    check('new task uses selected calendar day',()=>assert.equal(getState().tasks.find(t=>t.title==='日历新建验证').dueDate,date));
    await value('.calendar-agenda .quick-add input','日历快速添加验证');await js('document.querySelector(".calendar-agenda .quick-add").requestSubmit()');await saved();
    check('quick add uses selected calendar day',()=>assert.equal(getState().tasks.find(t=>t.title==='日历快速添加验证').dueDate,date));
    const added=getState().tasks.find(t=>t.title==='日历新建验证'),moved=model.addDays(date,1);
    await click(`.calendar-task[data-id="${added.id}"]`);await value('[name=dueDate]',moved);await js('document.querySelector("#task-form").requestSubmit()');await saved();
    assert.equal(await js(`document.querySelector('.calendar-day[data-date="${moved}"] .day-count').textContent`),String(getState().tasks.filter(t=>!t.completed&&t.dueDate===moved).length));
    checks.push('editing date moves task to the correct calendar day');
    const quick=getState().tasks.find(t=>t.title==='日历快速添加验证');
    await click(`.calendar-agenda [data-action="complete"][data-id="${quick.id}"]`);await saved();
    assert.equal(await js(`document.querySelectorAll('.calendar-task[data-id="${quick.id}"]').length`),0);
    check('calendar completion saves and removes pending day marker',()=>assert.ok(getState().tasks.find(t=>t.id===quick.id).completed));
    await value('#calendar-month','2026-12');await js('document.querySelector("#calendar-month").dispatchEvent(new Event("change",{bubbles:true}))');
    await click('[data-action="calendar-month"][data-offset="1"]');
    assert.equal(await js('document.querySelector("#calendar-month").value'),'2027-01');
    await value('#calendar-month','2028-02');await js('document.querySelector("#calendar-month").dispatchEvent(new Event("change",{bubbles:true}))');
    assert.equal(await js(`document.querySelectorAll('.calendar-day[data-date="2028-02-29"]').length`),1);
    await click('.calendar-day[data-date="2028-01-31"]');
    assert.equal(await js('document.querySelector("#calendar-month").value'),'2028-01');
    await click('[data-action="calendar-today"]');
    assert.equal(await js('document.querySelector(".selected-day").dataset.date'),today);
    checks.push('calendar handles year change, leap day, adjacent month and return to today');
    await commit(model.demoState());await reload();await click('[data-view="scheduled"]');await screenshot('calendar');
    win.setSize(1060,700);await sleep(200);await screenshot('calendar-compact');
    await value('#calendar-month','2026-08');await js('document.querySelector("#calendar-month").dispatchEvent(new Event("change",{bubbles:true}))');await screenshot('calendar-six-weeks');
    assert.equal(await js('document.querySelectorAll(".calendar-day").length'),42);
    assert.ok(await js('document.body.scrollWidth<=innerWidth && document.querySelector(".calendar-grid").scrollWidth<=document.querySelector(".calendar-grid").clientWidth'));
    assert.ok(await js('document.querySelector(".calendar-grid").getBoundingClientRect().bottom<=document.querySelector(".calendar-content").getBoundingClientRect().bottom'));
    checks.push('compact six-week calendar fits window width');
    win.setSize(1440,930);await sleep(200);await click('[data-action="calendar-today"]');
    await click('[data-view="matrix"]');await screenshot('matrix');
    await click('[data-action="edit-task"]');await screenshot('task-editor');await click('[data-action="close-modal"]');
    await click('[data-action="settings"]');await click('[data-setting="theme"]');await saved();await click('[data-action="close-modal"]');await screenshot('dark');
    await click('[data-action="settings"]');await click('[data-setting="theme"]');await saved();await click('[data-action="close-modal"]');
    win.setSize(1060,700);await sleep(300);await screenshot('compact');
    const overflows=await js(`(()=>{const el=document.querySelector('.workspace');return {width:el.scrollWidth,client:el.clientWidth,body:document.body.scrollWidth,viewport:window.innerWidth};})()`);
    check('minimum window does not overflow horizontally',()=>assert.ok(overflows.body<=overflows.viewport&&overflows.width<=overflows.client));
    win.setSize(1440,930);await sleep(200);await click('[data-view="all"]');
    await click('[data-action="search"]');await value('#search-form input','第一版');await js('document.querySelector("#search-form").requestSubmit()');
    assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);checks.push('global search filters results');
    await click('[data-action="clear-search"]');await click('[data-view="completed"]');assert.equal(await js('document.querySelectorAll("[data-task]").length'),1);checks.push('completed archive');
    const stored=JSON.parse(await fs.readFile(dataFile,'utf8'));assert.equal(stored.tasks.length,8);assert.ok((await fs.stat(path.join(path.dirname(dataFile),'tasks.backup.json'))).size>0);checks.push('atomic file save and recovery snapshot');
    assert.deepEqual(errors,[]);checks.push('no renderer errors');
    await fs.writeFile(path.join(root,'test-results.json'),JSON.stringify({passed:checks.length,checks,errors},null,2),'utf8');
    console.log(`Desktop checks passed: ${checks.length}`);app.exit(0);
  }catch(e){console.error(e);await fs.writeFile(path.join(root,'test-results.json'),JSON.stringify({passed:checks.length,checks,error:e.stack,errors},null,2));try{await screenshot('failure');}catch{}app.exit(1);}
};
